#!/usr/bin/env python3
"""
Sweep DR-MPPI over Wasserstein radii (dr_eps_cvar) and plot collision probability vs epsilon.

Example:
  python3 stats/DR_stat.py --scenario 2 --runs 100 --steps 900 --use_gpu
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter, MultipleLocator
import numpy as np
import pandas as pd
import torch

import benchmark_mppi_stats as bench


DEFAULT_EPSILONS = np.arange(0.0, 0.1001, 0.005, dtype=np.float64)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Run DR-MPPI statistics for a sweep of dr_eps_cvar values.")
    ap.add_argument("--scenario", type=int, choices=[1, 2], default=1, help="Scenario 1 uses the straight-road setup; scenario 2 uses the roundabout setup.")
    ap.add_argument("--csv", type=str, default="", help="Optional override path to obstacle CSV. If omitted, the file is chosen from --scenario.")
    ap.add_argument("--runs", type=int, default=100)
    ap.add_argument("--outdir", type=str, default="results_dr_eps_stats")
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--steps", type=int, default=900)
    ap.add_argument("--alpha", type=float, default=0.95, help="CVaR alpha used by DR-MPPI.")
    ap.add_argument("--use_gpu", action="store_true")
    ap.add_argument(
        "--epsilons",
        type=float,
        nargs="+",
        default=None,
        help=(
            "Optional explicit list of dr_eps_cvar values to sweep. "
            "Example: --epsilons 0.0 0.005 0.01 0.015 0.02 0.025 0.03 0.035 0.04 0.045 0.05 0.055 0.06 0.065 0.07 0.075 0.08 0.085 0.09 0.095 0.1"
        ),
    )
    ap.add_argument(
        "--eps-max",
        type=float,
        default=None,
        help=(
            "Optional maximum epsilon for a uniform sweep from 0 to this value, inclusive. "
            "Used only when --epsilons is not provided."
        ),
    )
    ap.add_argument(
        "--eps-step",
        type=float,
        default=0.005,
        help=(
            "Step size for the uniform epsilon sweep generated by --eps-max. "
            "Ignored when --epsilons is provided."
        ),
    )
    ap.add_argument(
        "--obs-update-steps",
        type=int,
        default=20,
        help=(
            "Read a fresh obstacle CSV sample every N control steps and hold that "
            "same obstacle observation between reads. Control dt is unchanged."
        ),
    )
    ap.add_argument(
        "--obs-update-dt",
        type=float,
        default=None,
        help=(
            "Optional observation update period in seconds. When set, this overrides "
            "--obs-update-steps and uses the nearest available control tick, so control "
            "dt is still unchanged."
        ),
    )
    ap.add_argument(
        "--extra-sim-time",
        type=float,
        default=8.0,
        help=(
            "Optional extra simulation time in seconds after the last CSV timestamp. "
            "Beyond the CSV range, the last available obstacle sample is held."
        ),
    )
    ap.add_argument(
        "--pdf",
        action="store_true",
        help="Also save the collision-probability plot as PDF.",
    )
    return ap.parse_args()


def build_epsilon_sweep(args: argparse.Namespace) -> np.ndarray:
    if args.epsilons is not None:
        eps = np.asarray(args.epsilons, dtype=np.float64)
    elif args.eps_max is not None:
        eps_max = float(args.eps_max)
        eps_step = float(args.eps_step)
        if not (np.isfinite(eps_max) and eps_max >= 0.0):
            raise ValueError(f"--eps-max must be >= 0, got {args.eps_max}")
        if not (np.isfinite(eps_step) and eps_step > 0.0):
            raise ValueError(f"--eps-step must be > 0, got {args.eps_step}")
        count = int(np.floor(eps_max / eps_step + 1e-12)) + 1
        eps = eps_step * np.arange(count, dtype=np.float64)
        if eps.size == 0 or abs(float(eps[-1]) - eps_max) > 1e-12:
            eps = np.append(eps, eps_max)
    else:
        eps = DEFAULT_EPSILONS.copy()

    if eps.size == 0:
        raise ValueError("The epsilon sweep is empty.")
    if np.any(~np.isfinite(eps)):
        raise ValueError("All epsilon values must be finite.")
    if np.any(eps < 0.0):
        raise ValueError("All epsilon values must be non-negative.")

    eps = np.unique(np.round(eps, decimals=12))
    return np.sort(eps)


def build_sim_setup(args: argparse.Namespace) -> tuple[bench.plain_mod.MovingObstacleCSV, np.ndarray, dict, dict, str]:
    scenario = int(args.scenario)
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    default_csv_name = "obstacle_data.csv" if scenario == 1 else "obstacle_data_2.csv"
    default_csv = os.path.join(base_dir, "Data", default_csv_name)
    csv_path = args.csv if args.csv else default_csv

    pos_scale = 0.10
    vel_scale = 0.10
    acc_scale = 0.10
    y_offset = 23.0

    obs_csv = bench.plain_mod.MovingObstacleCSV(
        csv_path=csv_path,
        x_offset=0.0,
        y_offset=y_offset,
        pos_scale=pos_scale,
        vel_scale=vel_scale,
        acc_scale=acc_scale,
    )

    dt = float(np.round(np.min(np.diff(obs_csv.times)), 6))
    if not (np.isfinite(dt) and dt > 0):
        raise ValueError(f"Invalid dt computed from CSV: dt={dt}")

    obs_update_steps = max(1, int(args.obs_update_steps))
    obs_update_dt = None if args.obs_update_dt is None else float(args.obs_update_dt)
    extra_sim_time = float(args.extra_sim_time)
    if obs_update_dt is not None and not (np.isfinite(obs_update_dt) and obs_update_dt > 0.0):
        raise ValueError(f"--obs-update-dt must be positive, got {args.obs_update_dt}")
    if not (np.isfinite(extra_sim_time) and extra_sim_time >= 0.0):
        raise ValueError(f"--extra-sim-time must be >= 0, got {args.extra_sim_time}")

    csv_t_start = float(obs_csv.times[0])
    csv_t_end = float(obs_csv.times[-1])
    sim_steps_total = max(
        len(obs_csv.times),
        int(np.ceil((csv_t_end + extra_sim_time - csv_t_start) / dt - 1e-9)) + 1,
    )
    sim_time_grid = csv_t_start + dt * np.arange(sim_steps_total, dtype=float)
    steps = min(int(args.steps), len(sim_time_grid))
    sim_time_grid = sim_time_grid[:steps]

    # Match the current DR_mppi.py parameter block.
    T = 20
    M = 1200
    lam = 2.0
    sigma = np.array([2.0, 1.04], dtype=np.float32)
    u_min = np.array([0.0, -np.deg2rad(180.0)], dtype=np.float32)
    u_max = np.array([5.0, np.deg2rad(180.0)], dtype=np.float32)

    Q = np.array([0.001, 0.01, 0.001], dtype=np.float32)
    Qf = np.array([0.5, 50.0, 1.0], dtype=np.float32)
    R = np.array([0.004, 0.004], dtype=np.float32)
    cvar_N = 10
    obs_pos_sigma = (0.07, 0.07)
    obs_noise_mode = "per_step"
    risk_cost_A = 10.0
    risk_cost_Cu = 0.0

    lane_psi = 0.0
    L_ref = 5.0
    v_des = 5.0
    u_blend_v = 1.0

    ROAD_CENTER = 1.0
    LANE_W = 0.80
    y_divider = ROAD_CENTER
    y_bottom = ROAD_CENTER - LANE_W
    y_top = ROAD_CENTER + LANE_W
    y_divider_top_1 = ROAD_CENTER + LANE_W
    y_divider_top_2 = y_divider_top_1 + LANE_W
    y_top_outer = y_top + 2.0 * LANE_W
    lane_y = ROAD_CENTER + 0.5 * LANE_W
    y_min_bound = 0.0
    y_max_bound = y_divider_top_1
    boundary_w = 500.0
    boundary_k = 50.0
    boundary_d = 0.05
    path_boundary_w = 0.0
    path_boundary_k = 35.0
    path_corridor_radius = 0.45

    ego_length = 4.5 * pos_scale
    ego_width = 1.8 * pos_scale
    ego_radius = 0.5 * np.sqrt(ego_length**2 + ego_width**2)
    obs_radius = ego_radius

    plan_extra_margin = 0.0
    eval_extra_margin = 0.0

    ref_path_xypsi = None
    ref_path_s = None
    ref_nearest_idx0 = 0
    x0 = np.array([0.0, lane_y, 0.0], dtype=np.float32)
    if scenario == 2:
        roundabout_center_x = 6.1
        roundabout_center_y = lane_y
        L_ref = 1.6
        v_des = 2.8
        boundary_w = 0.0
        path_boundary_w = 300.0
        ref_waypoints_xy = bench.plain_mod.build_roundabout_waypoints(roundabout_center_x, roundabout_center_y)
        ref_path_xypsi, ref_path_s = bench.plain_mod.build_path_from_waypoints(ref_waypoints_xy, ds=0.05)
        x0 = ref_path_xypsi[0].astype(np.float32)

    params = dict(
        scenario=scenario,
        dt=dt,
        steps=steps,
        T=T,
        M=M,
        x0=x0,
        lane_y=lane_y,
        lane_psi=lane_psi,
        L_ref=L_ref,
        v_des=v_des,
        u_blend_v=u_blend_v,
        u_min=u_min,
        u_max=u_max,
        sigma=sigma,
        Q=Q,
        R=R,
        Qf=Qf,
        plain_obs_w=0.0,
        ego_radius=ego_radius,
        obs_radius=obs_radius,
        y_bottom=y_bottom,
        y_top=y_top,
        y_divider=y_divider,
        y_divider_top_1=y_divider_top_1,
        y_divider_top_2=y_divider_top_2,
        y_top_outer=y_top_outer,
        y_min_bound=y_min_bound,
        y_max_bound=y_max_bound,
        boundary_w=boundary_w,
        boundary_k=boundary_k,
        boundary_d=boundary_d,
        path_boundary_w=path_boundary_w,
        path_boundary_k=path_boundary_k,
        path_corridor_radius=path_corridor_radius,
        ref_path_xypsi=ref_path_xypsi,
        ref_path_s=ref_path_s,
        ref_nearest_idx0=ref_nearest_idx0,
        plan_extra_margin=plan_extra_margin,
        eval_extra_margin=eval_extra_margin,
        x_ahead=18.0,
        x_behind=4.0,
        y_halfspan=2.8,
        max_obs_draw=20,
        dyn_w_max=np.deg2rad(180.0),
        obs_update_steps=obs_update_steps,
        obs_update_dt=obs_update_dt,
    )

    device = "cuda" if (args.use_gpu and torch.cuda.is_available()) else "cpu"
    print(
        f"[setup] scenario={scenario}, csv={csv_path}, requested_gpu={int(bool(args.use_gpu))}, "
        f"torch_cuda_available={int(bool(torch.cuda.is_available()))}, device={device}",
        flush=True,
    )
    if obs_update_dt is None:
        print(
            f"[OBS] control_dt={dt:.6f} s | fresh CSV obstacle read every "
            f"{obs_update_steps} control step(s) = {obs_update_steps * dt:.6f} s; held between reads",
            flush=True,
        )
    else:
        print(
            f"[OBS] control_dt={dt:.6f} s | requested fresh CSV obstacle read period "
            f"{obs_update_dt:.6f} s; using nearest control tick and holding between reads",
            flush=True,
        )
    print(
        f"[SIM] csv_time_range=[{csv_t_start:.3f}, {csv_t_end:.3f}] s | "
        f"run_time_range=[{sim_time_grid[0]:.3f}, {sim_time_grid[-1]:.3f}] s",
        flush=True,
    )
    if sim_time_grid[-1] > csv_t_end + 1e-9:
        print("[SIM] past the last CSV timestamp, the last available obstacle sample is held.", flush=True)

    common_kwargs = dict(
        dt=dt,
        T=T,
        M=M,
        lam=lam,
        noise_sigma=sigma,
        u_min=u_min,
        u_max=u_max,
        device=device,
        dtype=torch.float32,
        verbose=False,
        dyn_kwargs=dict(w_max=float(params["dyn_w_max"])),
        cost_kwargs=dict(
            ref=None,
            Q=None,
            R=None,
            Qf=None,
            O_mean=None,
            radii=None,
            obs_w=0.0,
            y_min=None,
            y_max=None,
            boundary_w=0.0,
            boundary_k=boundary_k,
            boundary_d=boundary_d,
            path_xy=None,
            path_corridor_radius=path_corridor_radius,
            path_boundary_w=0.0,
            path_boundary_k=path_boundary_k,
        ),
    )

    dr_cfg = dict(
        cvar_N=cvar_N,
        obs_pos_sigma=obs_pos_sigma,
        obs_noise_mode=obs_noise_mode,
        risk_cost_A=risk_cost_A,
        risk_cost_Cu=risk_cost_Cu,
    )
    return obs_csv, sim_time_grid, params, common_kwargs, device, dr_cfg


def make_controller(common_kwargs: dict, dr_cfg: dict, alpha: float, dr_eps_cvar: float):
    return bench.DRMPPIClass(
        dynamics=bench.dr_mod.dyn_diffdrive,
        running_cost=bench.dr_mod.running_cost_lane_obs,
        terminal_cost=bench.dr_mod.terminal_cost_track,
        cvar_alpha=float(alpha),
        cvar_N=int(dr_cfg["cvar_N"]),
        obs_pos_sigma=dr_cfg["obs_pos_sigma"],
        obs_noise_mode=str(dr_cfg["obs_noise_mode"]),
        dr_eps_cvar=float(dr_eps_cvar),
        risk_cost_A=float(dr_cfg["risk_cost_A"]),
        risk_cost_Cu=float(dr_cfg["risk_cost_Cu"]),
        **common_kwargs,
    )


def log_controller_device_status(ctrl, requested_gpu: bool) -> None:
    ctrl_device = getattr(ctrl, "device", torch.device("cpu"))
    ctrl_device = torch.device(ctrl_device)

    u_device = None
    if hasattr(ctrl, "U") and isinstance(ctrl.U, torch.Tensor):
        u_device = ctrl.U.device

    print(
        f"[DEVICE] controller_device={ctrl_device}, controller_uses_gpu={int(ctrl_device.type == 'cuda')}",
        flush=True,
    )
    if u_device is not None:
        print(f"[DEVICE] control_tensor_device={u_device}", flush=True)

    if ctrl_device.type == "cuda":
        gpu_index = ctrl_device.index if ctrl_device.index is not None else torch.cuda.current_device()
        gpu_name = torch.cuda.get_device_name(gpu_index)
        print(f"[DEVICE] gpu_name={gpu_name}", flush=True)
    elif requested_gpu:
        print(
            "[DEVICE] WARNING: --use_gpu was requested, but the controller is running on CPU.",
            flush=True,
        )


def save_collision_plot(summary_df: pd.DataFrame, outdir: Path, scenario: int, save_pdf: bool) -> None:
    epsilon_values = summary_df["epsilon"].to_numpy(dtype=float)
    max_epsilon = float(np.max(epsilon_values)) if len(epsilon_values) > 0 else 0.0
    x_pad = max(0.0025, 0.02 * max_epsilon)

    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    ax.plot(
        epsilon_values,
        summary_df["collision_prob"].to_numpy(dtype=float),
        linewidth=2.0,
        color="#0072B2",
        label="Collision probability",
    )
    ax.set_xlabel("Wasserstein radius, $\\varepsilon$")
    ax.set_ylabel("Collision probability")
    ax.set_xlim(-x_pad, max_epsilon + x_pad)
    ax.set_ylim(-0.02, 1.02)
    ax.xaxis.set_major_locator(MultipleLocator(0.02))
    ax.xaxis.set_major_formatter(FormatStrFormatter("%.2f"))
    ax.yaxis.set_major_locator(MultipleLocator(0.2))
    ax.yaxis.set_major_formatter(FormatStrFormatter("%.1f"))
    ax.set_title(f"DR-MPPI Collision Probability vs. Wasserstein Radius | Scenario {scenario}")
    ax.grid(True, alpha=0.3)
    ax.legend()
    png_path = outdir / "dr_epsilon_collision_probability.png"
    plt.savefig(png_path, dpi=300, bbox_inches="tight")
    if save_pdf:
        pdf_path = outdir / "dr_epsilon_collision_probability.pdf"
        plt.savefig(pdf_path, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    eps_sweep = build_epsilon_sweep(args)

    obs_csv, sim_time_grid, params, common_kwargs, _device, dr_cfg = build_sim_setup(args)

    master = np.random.default_rng(int(args.seed))
    run_seeds = master.integers(0, 2**31 - 1, size=int(args.runs), dtype=np.int64)

    run_rows: list[dict] = []
    summary_rows: list[dict] = []
    device_checked = False

    print(f"[epsilon sweep] values={eps_sweep.tolist()}", flush=True)

    for eps in eps_sweep:
        print(f"[epsilon] dr_eps_cvar={eps:.6f}", flush=True)
        ctrl = make_controller(common_kwargs=common_kwargs, dr_cfg=dr_cfg, alpha=float(args.alpha), dr_eps_cvar=float(eps))
        if not device_checked:
            log_controller_device_status(ctrl=ctrl, requested_gpu=bool(args.use_gpu))
            device_checked = True

        per_eps_cost = []
        per_eps_min_dist = []
        per_eps_safety = []
        per_eps_collision = []
        per_eps_tmax = []

        for run_idx in range(int(args.runs)):
            run_seed = int(run_seeds[run_idx])
            ctrl.U[:] = 0.0
            ctrl.U[-1] = np.array([params["v_des"], 0.0], dtype=np.float32)
            ctrl.U_cpu = ctrl.U

            total_qr_cost, dists, safety_violated, collided, max_compute_s = bench.run_episode(
                ctrl=ctrl,
                kind="dr",
                obs_csv=obs_csv,
                sim_time_grid=sim_time_grid,
                params=params,
                run_seed=run_seed,
            )

            d = np.asarray(dists, dtype=np.float64)
            d = d[np.isfinite(d)]
            run_min_d = float(np.min(d)) if len(d) > 0 else np.nan
            safety_f = 1.0 if safety_violated else 0.0
            collided_f = 1.0 if collided else 0.0
            tmax_ms = 1000.0 * float(max_compute_s)

            per_eps_cost.append(float(total_qr_cost))
            per_eps_min_dist.append(run_min_d)
            per_eps_safety.append(safety_f)
            per_eps_collision.append(collided_f)
            per_eps_tmax.append(tmax_ms)

            run_rows.append(
                dict(
                    epsilon=float(eps),
                    Run=run_idx,
                    Seed=run_seed,
                    RunMinDistance=run_min_d,
                    SafetyViolation=safety_f,
                    Collision=collided_f,
                    TotalQRCost=float(total_qr_cost),
                    RunMaxComputeTimeMs=tmax_ms,
                )
            )

            print(
                f"  [run {run_idx + 1:3d}/{args.runs}] "
                f"min_dist={run_min_d:.4f} safety={int(safety_violated)} collided={int(collided)}",
                flush=True,
            )

        d = np.asarray(per_eps_min_dist, dtype=np.float64)
        d_f = d[np.isfinite(d)]
        safety = np.asarray(per_eps_safety, dtype=np.float64)
        collision = np.asarray(per_eps_collision, dtype=np.float64)
        cost = np.asarray(per_eps_cost, dtype=np.float64)
        tmax = np.asarray(per_eps_tmax, dtype=np.float64)

        collision_prob = float(np.mean(collision))
        collision_free_prob = 1.0 - collision_prob
        safety_violation_prob = float(np.mean(safety))

        summary_rows.append(
            dict(
                epsilon=float(eps),
                collision_prob=collision_prob,
                collision_free_prob=collision_free_prob,
                safety_violation_prob=safety_violation_prob,
                run_min_distance_min=float(np.min(d_f)) if len(d_f) > 0 else np.nan,
                run_min_distance_mean=float(np.mean(d_f)) if len(d_f) > 0 else np.nan,
                run_min_distance_std=float(np.std(d_f, ddof=1)) if len(d_f) > 1 else 0.0,
                total_qr_cost_mean=float(np.mean(cost)),
                total_qr_cost_std=float(np.std(cost, ddof=1)) if len(cost) > 1 else 0.0,
                run_max_compute_time_ms_mean=float(np.mean(tmax)) if len(tmax) > 0 else np.nan,
                run_max_compute_time_ms_std=float(np.std(tmax, ddof=1)) if len(tmax) > 1 else 0.0,
            )
        )
        print(
            f"  [epsilon summary] eps={eps:.6f} collision_prob={collision_prob:.4f} "
            f"collision_free_prob={collision_free_prob:.4f}",
            flush=True,
        )

    run_df = pd.DataFrame(run_rows)
    summary_df = pd.DataFrame(summary_rows).sort_values("epsilon").reset_index(drop=True)

    run_csv = outdir / "dr_epsilon_run_metrics.csv"
    summary_csv = outdir / "dr_epsilon_summary.csv"
    run_df.to_csv(run_csv, index=False)
    summary_df.to_csv(summary_csv, index=False)

    save_collision_plot(summary_df=summary_df, outdir=outdir, scenario=int(args.scenario), save_pdf=bool(args.pdf))

    print(f"[OK] wrote: {run_csv}", flush=True)
    print(f"[OK] wrote: {summary_csv}", flush=True)
    print(f"[OK] wrote: {outdir / 'dr_epsilon_collision_probability.png'}", flush=True)
    if args.pdf:
        print(f"[OK] wrote: {outdir / 'dr_epsilon_collision_probability.pdf'}", flush=True)


if __name__ == "__main__":
    main()
