#!/usr/bin/env python3
"""
Parallel sweep of DR-MPPI over Wasserstein radii (dr_eps_cvar).

This script keeps the original DR_stat.py behavior and outputs, but runs
independent epsilon values in parallel on CPU workers.

Example:
    python3 stats/DR_stat_parallel.py --scenario 2 --runs 100 --steps 700 --eps-max 0.1 --eps-step 0.001 --workers 8
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import contextlib
import io
import multiprocessing as mp
import os
from pathlib import Path
import time
from typing import Any

import numpy as np
import pandas as pd
import torch

import benchmark_mppi_stats as bench
import DR_stat as serial_dr


_WORKER_STATE: dict[str, Any] = {}


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Run DR-MPPI statistics for a sweep of dr_eps_cvar values in parallel.")
    ap.add_argument("--scenario", type=int, choices=[1, 2], default=1, help="Scenario 1 uses the straight-road setup; scenario 2 uses the roundabout setup.")
    ap.add_argument("--csv", type=str, default="", help="Optional override path to obstacle CSV. If omitted, the file is chosen from --scenario.")
    ap.add_argument("--runs", type=int, default=100)
    ap.add_argument("--outdir", type=str, default="results_dr_eps_stats")
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--steps", type=int, default=900)
    ap.add_argument("--alpha", type=float, default=0.95, help="CVaR alpha used by DR-MPPI.")
    ap.add_argument("--use_gpu", action="store_true")
    ap.add_argument(
        "--epsilons",
        type=float,
        nargs="+",
        default=None,
        help=(
            "Optional explicit list of dr_eps_cvar values to sweep. "
            "Example: --epsilons 0.0 0.005 0.01 0.015 0.02 0.025 0.03 0.035 0.04 0.045 0.05 0.055 0.06 0.065 0.07 0.075 0.08 0.085 0.09 0.095 0.1"
        ),
    )
    ap.add_argument(
        "--eps-max",
        type=float,
        default=None,
        help=(
            "Optional maximum epsilon for a uniform sweep from 0 to this value, inclusive. "
            "Used only when --epsilons is not provided."
        ),
    )
    ap.add_argument(
        "--eps-step",
        type=float,
        default=0.005,
        help=(
            "Step size for the uniform epsilon sweep generated by --eps-max. "
            "Ignored when --epsilons is provided."
        ),
    )
    ap.add_argument(
        "--obs-update-steps",
        type=int,
        default=10,
        help=(
            "Read a fresh obstacle CSV sample every N control steps and hold that "
            "same obstacle observation between reads. Control dt is unchanged."
        ),
    )
    ap.add_argument(
        "--obs-update-dt",
        type=float,
        default=None,
        help=(
            "Optional observation update period in seconds. When set, this overrides "
            "--obs-update-steps and uses the nearest available control tick, so control "
            "dt is still unchanged."
        ),
    )
    ap.add_argument(
        "--extra-sim-time",
        type=float,
        default=8.0,
        help=(
            "Optional extra simulation time in seconds after the last CSV timestamp. "
            "Beyond the CSV range, the last available obstacle sample is held."
        ),
    )
    ap.add_argument(
        "--pdf",
        action="store_true",
        help="Also save the collision-probability plot as PDF.",
    )
    ap.add_argument(
        "--workers",
        type=int,
        default=0,
        help=(
            "Number of parallel worker processes for the epsilon sweep. "
            "Use 0 for auto. In GPU mode, use --workers N explicitly to run N CUDA worker processes."
        ),
    )
    ap.add_argument(
        "--torch-threads-per-worker",
        type=int,
        default=0,
        help=(
            "Optional CPU thread cap inside each worker. "
            "Use 0 to keep PyTorch defaults, or let the script auto-cap to 1 when running multiple CPU workers."
        ),
    )
    ap.add_argument(
        "--log-runs-every",
        type=int,
        default=10,
        help=(
            "Print worker-side progress every N runs within each epsilon job. "
            "Use 0 to disable per-run progress logs."
        ),
    )
    return ap.parse_args()


def _choose_workers(args: argparse.Namespace, num_eps: int) -> int:
    requested = int(args.workers)
    if requested < 0:
        raise ValueError(f"--workers must be >= 0, got {args.workers}")

    if requested == 0:
        if bool(args.use_gpu):
            return 1
        cpu_count = os.cpu_count() or 1
        requested = max(1, cpu_count - 1)

    if bool(args.use_gpu) and requested > 1:
        print(
            f"[parallel] --use_gpu with workers={requested}; launching multiple CUDA worker processes. "
            "Monitor VRAM with nvidia-smi.",
            flush=True,
        )

    return max(1, min(int(requested), int(num_eps)))


def _choose_torch_threads(args: argparse.Namespace, workers: int) -> int:
    requested = int(args.torch_threads_per_worker)
    if requested < 0:
        raise ValueError(
            f"--torch-threads-per-worker must be >= 0, got {args.torch_threads_per_worker}"
        )
    if requested > 0:
        return requested
    if bool(args.use_gpu) or workers <= 1:
        return 0
    return 1


def _args_to_worker_dict(args: argparse.Namespace) -> dict[str, Any]:
    return dict(
        scenario=int(args.scenario),
        csv=str(args.csv),
        runs=int(args.runs),
        outdir=str(args.outdir),
        seed=int(args.seed),
        steps=int(args.steps),
        alpha=float(args.alpha),
        use_gpu=bool(args.use_gpu),
        epsilons=None,
        eps_max=float(args.eps_max) if args.eps_max is not None else None,
        eps_step=float(args.eps_step),
        obs_update_steps=int(args.obs_update_steps),
        obs_update_dt=float(args.obs_update_dt) if args.obs_update_dt is not None else None,
        extra_sim_time=float(args.extra_sim_time),
        pdf=bool(args.pdf),
        workers=int(args.workers),
        torch_threads_per_worker=int(args.torch_threads_per_worker),
        log_runs_every=int(args.log_runs_every),
    )


def _build_worker_context(args_dict: dict[str, Any], torch_threads: int = 0, quiet: bool = False) -> dict[str, Any]:
    args = argparse.Namespace(**args_dict)
    if torch_threads > 0 and not bool(args.use_gpu):
        torch.set_num_threads(int(torch_threads))
        try:
            torch.set_num_interop_threads(1)
        except RuntimeError:
            pass

    if quiet:
        with contextlib.redirect_stdout(io.StringIO()):
            obs_csv, sim_time_grid, params, common_kwargs, _device, dr_cfg = serial_dr.build_sim_setup(args)
    else:
        obs_csv, sim_time_grid, params, common_kwargs, _device, dr_cfg = serial_dr.build_sim_setup(args)
    return dict(
        alpha=float(args.alpha),
        runs=int(args.runs),
        log_runs_every=max(0, int(getattr(args, "log_runs_every", 0))),
        obs_csv=obs_csv,
        sim_time_grid=sim_time_grid,
        params=params,
        common_kwargs=common_kwargs,
        dr_cfg=dr_cfg,
    )


def _format_duration(seconds: float) -> str:
    seconds = max(0.0, float(seconds))
    total = int(round(seconds))
    hours, rem = divmod(total, 3600)
    minutes, secs = divmod(rem, 60)
    if hours > 0:
        return f"{hours:d}h{minutes:02d}m{secs:02d}s"
    if minutes > 0:
        return f"{minutes:d}m{secs:02d}s"
    return f"{secs:d}s"


def _summarize_one_epsilon(eps: float, run_rows: list[dict[str, Any]]) -> dict[str, Any]:
    min_d = np.asarray([row["RunMinDistance"] for row in run_rows], dtype=np.float64)
    min_d_f = min_d[np.isfinite(min_d)]
    safety = np.asarray([row["SafetyViolation"] for row in run_rows], dtype=np.float64)
    collision = np.asarray([row["Collision"] for row in run_rows], dtype=np.float64)
    total_qr_cost = np.asarray([row["TotalQRCost"] for row in run_rows], dtype=np.float64)
    tmax = np.asarray([row["RunMaxComputeTimeMs"] for row in run_rows], dtype=np.float64)

    collision_prob = float(np.mean(collision))
    return dict(
        epsilon=float(eps),
        collision_prob=collision_prob,
        collision_free_prob=1.0 - collision_prob,
        safety_violation_prob=float(np.mean(safety)),
        run_min_distance_min=float(np.min(min_d_f)) if len(min_d_f) > 0 else np.nan,
        run_min_distance_mean=float(np.mean(min_d_f)) if len(min_d_f) > 0 else np.nan,
        run_min_distance_std=float(np.std(min_d_f, ddof=1)) if len(min_d_f) > 1 else 0.0,
        total_qr_cost_mean=float(np.mean(total_qr_cost)),
        total_qr_cost_std=float(np.std(total_qr_cost, ddof=1)) if len(total_qr_cost) > 1 else 0.0,
        run_max_compute_time_ms_mean=float(np.mean(tmax)) if len(tmax) > 0 else np.nan,
        run_max_compute_time_ms_std=float(np.std(tmax, ddof=1)) if len(tmax) > 1 else 0.0,
    )


def _run_one_epsilon_from_context(
    eps: float,
    run_seeds: tuple[int, ...],
    context: dict[str, Any],
) -> dict[str, Any]:
    job_t0 = time.perf_counter()
    ctrl = serial_dr.make_controller(
        common_kwargs=context["common_kwargs"],
        dr_cfg=context["dr_cfg"],
        alpha=float(context["alpha"]),
        dr_eps_cvar=float(eps),
    )
    params = context["params"]
    total_runs = int(context["runs"])
    log_runs_every = int(context["log_runs_every"])
    worker_pid = os.getpid()

    run_rows: list[dict[str, Any]] = []
    print(
        f"[worker pid={worker_pid}] eps={eps:.6f} started "
        f"runs={total_runs} steps={int(params['steps'])}",
        flush=True,
    )
    for run_idx, run_seed in enumerate(run_seeds):
        ctrl.U[:] = 0.0
        ctrl.U[-1] = np.array([params["v_des"], 0.0], dtype=np.float32)
        ctrl.U_cpu = ctrl.U

        total_qr_cost, dists, safety_violated, collided, max_compute_s = bench.run_episode(
            ctrl=ctrl,
            kind="dr",
            obs_csv=context["obs_csv"],
            sim_time_grid=context["sim_time_grid"],
            params=params,
            run_seed=int(run_seed),
        )

        d = np.asarray(dists, dtype=np.float64)
        d = d[np.isfinite(d)]
        run_rows.append(
            dict(
                epsilon=float(eps),
                Run=int(run_idx),
                Seed=int(run_seed),
                RunMinDistance=float(np.min(d)) if len(d) > 0 else np.nan,
                SafetyViolation=1.0 if safety_violated else 0.0,
                Collision=1.0 if collided else 0.0,
                TotalQRCost=float(total_qr_cost),
                RunMaxComputeTimeMs=1000.0 * float(max_compute_s),
            )
        )

        runs_done = run_idx + 1
        should_log = (
            log_runs_every > 0
            and (
                runs_done == 1
                or runs_done == total_runs
                or (runs_done % log_runs_every) == 0
            )
        )
        if should_log:
            elapsed = time.perf_counter() - job_t0
            avg_per_run = elapsed / float(runs_done)
            eta = avg_per_run * float(total_runs - runs_done)
            print(
                f"[worker pid={worker_pid}] eps={eps:.6f} "
                f"run={runs_done}/{total_runs} "
                f"elapsed={_format_duration(elapsed)} "
                f"eta={_format_duration(eta)}",
                flush=True,
            )

    return dict(
        epsilon=float(eps),
        duration_s=float(time.perf_counter() - job_t0),
        run_rows=run_rows,
        summary_row=_summarize_one_epsilon(eps=float(eps), run_rows=run_rows),
    )


def _init_worker(args_dict: dict[str, Any], run_seeds: tuple[int, ...], torch_threads: int) -> None:
    global _WORKER_STATE
    _WORKER_STATE = dict(
        context=_build_worker_context(args_dict=args_dict, torch_threads=torch_threads, quiet=True),
        run_seeds=tuple(int(seed) for seed in run_seeds),
    )


def _run_one_epsilon_worker(eps: float) -> dict[str, Any]:
    return _run_one_epsilon_from_context(
        eps=float(eps),
        run_seeds=_WORKER_STATE["run_seeds"],
        context=_WORKER_STATE["context"],
    )


def _log_one_result(result: dict[str, Any], done_count: int, total_count: int) -> None:
    summary = result["summary_row"]
    elapsed_total = float(result["elapsed_total_s"])
    remaining = max(0, int(total_count) - int(done_count))
    eta_total = (elapsed_total / float(done_count)) * float(remaining) if done_count > 0 else 0.0
    print(
        f"[done {done_count:3d}/{total_count}] eps={summary['epsilon']:.6f} "
        f"job_time={_format_duration(result['duration_s'])} "
        f"total_elapsed={_format_duration(elapsed_total)} "
        f"overall_eta={_format_duration(eta_total)} "
        f"collision_prob={summary['collision_prob']:.4f} "
        f"collision_free_prob={summary['collision_free_prob']:.4f}",
        flush=True,
    )


def main() -> None:
    args = parse_args()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    eps_sweep = serial_dr.build_epsilon_sweep(args)
    workers = _choose_workers(args=args, num_eps=len(eps_sweep))
    torch_threads = _choose_torch_threads(args=args, workers=workers)
    run_seeds = tuple(
        int(seed)
        for seed in np.random.default_rng(int(args.seed)).integers(
            0,
            2**31 - 1,
            size=int(args.runs),
            dtype=np.int64,
        )
    )
    args_dict = _args_to_worker_dict(args)

    # Reuse the original device check and setup logging once in the main process.
    _obs_csv, _sim_time_grid, _params, common_kwargs, _device, dr_cfg = serial_dr.build_sim_setup(args)
    ctrl = serial_dr.make_controller(
        common_kwargs=common_kwargs,
        dr_cfg=dr_cfg,
        alpha=float(args.alpha),
        dr_eps_cvar=float(eps_sweep[0]),
    )
    serial_dr.log_controller_device_status(ctrl=ctrl, requested_gpu=bool(args.use_gpu))
    del ctrl

    print(f"[epsilon sweep] values={eps_sweep.tolist()}", flush=True)
    print(
        f"[parallel] workers={workers} start_method=spawn "
        f"torch_threads_per_worker={torch_threads if torch_threads > 0 else 'default'}",
        flush=True,
    )
    print(
        f"[parallel] submitted_eps={len(eps_sweep)} runs_per_eps={int(args.runs)} "
        f"steps_per_run={int(args.steps)} log_runs_every={int(args.log_runs_every)}",
        flush=True,
    )

    results: list[dict[str, Any]] = []
    sweep_t0 = time.perf_counter()
    if workers == 1:
        context = dict(
            alpha=float(args.alpha),
            runs=int(args.runs),
            log_runs_every=max(0, int(args.log_runs_every)),
            obs_csv=_obs_csv,
            sim_time_grid=_sim_time_grid,
            params=_params,
            common_kwargs=common_kwargs,
            dr_cfg=dr_cfg,
        )
        for idx, eps in enumerate(eps_sweep, start=1):
            result = _run_one_epsilon_from_context(
                eps=float(eps),
                run_seeds=run_seeds,
                context=context,
            )
            result["elapsed_total_s"] = float(time.perf_counter() - sweep_t0)
            results.append(result)
            _log_one_result(result=result, done_count=idx, total_count=len(eps_sweep))
    else:
        ctx = mp.get_context("spawn")
        with ProcessPoolExecutor(
            max_workers=workers,
            mp_context=ctx,
            initializer=_init_worker,
            initargs=(args_dict, run_seeds, torch_threads),
        ) as executor:
            future_to_eps = {
                executor.submit(_run_one_epsilon_worker, float(eps)): float(eps)
                for eps in eps_sweep
            }
            done_count = 0
            for future in as_completed(future_to_eps):
                eps = future_to_eps[future]
                try:
                    result = future.result()
                except Exception as exc:
                    raise RuntimeError(
                        f"Parallel epsilon job failed for dr_eps_cvar={eps:.6f}"
                    ) from exc
                result["elapsed_total_s"] = float(time.perf_counter() - sweep_t0)
                results.append(result)
                done_count += 1
                _log_one_result(result=result, done_count=done_count, total_count=len(eps_sweep))

    results.sort(key=lambda item: float(item["epsilon"]))
    run_rows = [row for result in results for row in result["run_rows"]]
    summary_rows = [result["summary_row"] for result in results]

    run_df = pd.DataFrame(run_rows).sort_values(["epsilon", "Run"]).reset_index(drop=True)
    summary_df = pd.DataFrame(summary_rows).sort_values("epsilon").reset_index(drop=True)

    run_csv = outdir / "dr_epsilon_run_metrics.csv"
    summary_csv = outdir / "dr_epsilon_summary.csv"
    run_df.to_csv(run_csv, index=False)
    summary_df.to_csv(summary_csv, index=False)

    saved_plot_paths = serial_dr.save_collision_plot(
        summary_df=summary_df,
        outdir=outdir,
        scenario=int(args.scenario),
        save_pdf=bool(args.pdf),
    )

    print(f"[OK] wrote: {run_csv}", flush=True)
    print(f"[OK] wrote: {summary_csv}", flush=True)
    for path in saved_plot_paths:
        print(f"[OK] wrote: {path}", flush=True)


if __name__ == "__main__":
    main()
